### ISSUE TITLE
Do not support GPU 30**?

### ISSUE THREAD

**Issue by fereenwong** [guochengqian/openpoints#2]
Hi, thanks for your sharing.

This code can not work with GPU 3090?

**Comment by guochengqian** [comment]
hi @fereenwong 

please comment this line out when you install the library:

https://github.com/guochengqian/PointNeXt/blob/15c829024ad270a7e39674a835e058d6de28c2df/install.sh#L9

**Comment by fereenwong** [comment]
Hi, @guochengqian 
thanks a lot for your timely reply. I am trying to install it step by step. It does not help when I step over the line9.
 And the error occurs when it comes to 
https://github.com/guochengqian/PointNeXt/blob/15c829024ad270a7e39674a835e058d6de28c2df/install.sh#L35

**Comment by fereenwong** [comment]
By the way, the key error message is "nvcc fatal : unsupported GPU architecture 'compute_86' "

**Comment by guochengqian** [comment]
hi pointnet2 is the cpp library from: https://github.com/sshaoshuai/Pointnet2.PyTorch
I never used 3090, and I am sorry that I cannot help with this now. 
You might search for solutions online or in their Github repo

**Comment by fereenwong** [comment]
Hi, thanks for your reply. I will update the solutions if I get it work with GPU 3090. Maybe I will just use another server, hhh~

**Comment by ziyangyeh** [comment]
@fereenwong export TORCH_CUDA_ARCH_LIST="6.1;6.2;7.0;7.5;8.0;8.6"   # 3090:8.6; a100: 8.0; v100: 7.0; 2080ti: 7.5; titan xp: 6.1

**Comment by fereenwong** [comment]
@ziyangyeh thanks for your reply.
