### ISSUE TITLE
amp in pytorch lightning?

### ISSUE THREAD

**Issue by ziyangyeh** [guochengqian/openpoints#3]
Cannot use amp in pytorch-lightning whatever the backend is "native" or "nvidia-amp".
`pointnet2_cuda.group_points_wrapper(B, C, N, nfeatures, nsample, features, idx, output)`
`RuntimeError: expected scalar type Float but found Half`

**Comment by guochengqian** [comment]
could you check their documentation if you want to use pytorch-ligntning? bascially, how to warp an CPP extension in amp.
i am not an expert in this. sorry i can not help you

**Comment by ziyangyeh** [comment]
thank you for your reply.
