### ISSUE TITLE
ModelNet40 with normals

### ISSUE THREAD

**Issue by sheshap** [guochengqian/openpoints#4]
Hi,

Nice library.
Can you please support data loaders to support use of additional features such as normals?

Thanks in advance.

**Comment by guochengqian** [comment]
Thanks for the interest. Will do

**Comment by sheshap** [comment]
Hi, Can you please provide an update on this enhancement? Thanks

**Comment by sheshap** [comment]
@guochengqian, please do the needful. Thanks

**Comment by guochengqian** [comment]
available in https://github.com/guochengqian/openpoints/blob/master/dataset/modelnet/modelnet40_normal_resampled_loader.py
